version: 2.1

jobs:
  #DEBIAN
  job-0-debian:
    docker:
      - image: "debian:latest"
    steps:
      - checkout
      - run:
          name: Update and install sudo
          command: "apt-get update && apt-get install -y sudo &&  rm -rf /var/lib/apt/lists/* "
      - run:
          name: install qqy
          command: apt-get update -qqy && apt-get -qqy install
      - run:
          name: Install the required dev packages
          command: "apt-get install -yqq g++ python python3"
      - run:
          name: check what os we got and run platform dependent script
          command: cd projects/showdate/ && chmod 775 check_os.sh && ./check_os.sh
      # - run:
      #     name: checks integrity of the packages
      #     command: "g++ -v && which g++ &&gcc -v && which gcc && python --version && which python && python3 --version && which python3"
  # UBUNTU
  job-1-ubuntu:
    docker:
      - image: "ubuntu:latest"
    steps:
      - checkout
      - run:
          name: "set env vars again"
          command: |
            echo 'debconf debconf/frontend select Noninteractive' debconf-set-selections
            echo export DEBIAN_FRONTEND=noninteractive >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Update and install sudo
          command: "apt-get update && apt-get install -y sudo &&  rm -rf /var/lib/apt/lists/* "
      - run:
          name: install qqy
          command: apt-get update -qqy && apt-get -qqy install
      - run:
          name: Install the required packages
          command: "apt-get install -yqq g++ python python3"
      - run:
          name: check what os we got and run platform dependent script
          command: cd projects/showdate/ && chmod 775 check_os.sh && ./check_os.sh
      # - run:
      #     name: checks integrity of the packages
      #     command: "g++ -v && which g++ &&gcc -v && which gcc && python --version && which python && python3 --version && which python3"
  # CENTOS
  job-2-centos:
    docker:
      - image: "centos:latest"
    steps:
      - checkout
      - run:
          name: install updates
          command: yum -y update && yum -y upgrade
      - run:
          name: install which package so we can check what is good
          command: yum -y install which
      - run:
          name: install dev package
          command: dnf groupinstall -y "Development Tools"
      # - run:
      #     name: checks integrity of the packages
      #     command: "g++ -v && which g++ &&gcc -v && which gcc"
      - run:
          name: install python2 and python3 with dnf
          command: dnf install -y python2 python3
      - run:
          name: check what os we got and run platform dependent script
          command: cd projects/showdate/ && chmod 775 check_os.sh && ./check_os.sh
      - run:
          name: clean up the mess
          command: cd projects/showdate/ && chmod 775 wipebuild.sh && ./wipebuild.sh && ls -la
      # - run:
      #     name: install python 3 with dnf
      #     command: dnf -y install python3
      # - run:
      #     name: check python integrity
      #     command: which python2 && python2 --version && which python3 && python3 --version
      # - run:
      #     name: install dev package
      #     command: yum install -y python python3
      # - run:
      #     name: checks integrity of the packages
      #     command: "g++ -v && which g++ &&gcc -v && which gcc && python --version && which python && python3 --version && which python3"

workflows:
  version: 2.1
  start-containers:
    jobs:
      # - job-0-debian
      # - job-1-ubuntu
      - job-2-centos
