version: 2.1

jobs:

#DEBIAN
  job-0-debian:
    docker:
      - image: "debian:latest"
    steps:
      - checkout
      - run:
          name: Check platform
          command: " uname -a"
      - run:
          name: Check content of the repo
          command: "ls -la"

# UBUNTU
  job-1-ubuntu:
    docker:
      - image: "ubuntu:latest"
    steps:
      - checkout
      - run:
    name: "set env vars again"
    command: |
        echo 'debconf debconf/frontend select Noninteractive' debconf-set-selections
        echo export DEBIAN_FRONTEND=noninteractive >> $BASH_ENV
        source $BASH_ENV
      - run:
          name: Update and install sudo
          command: "apt-get update && apt-get install -y sudo &&  rm -rf /var/lib/apt/lists/* "
      - run:
          name: install qqy 
          command: apt-get update -qqy && apt-get -qqy install
      - run:
          name: check the frontend envar 
          command: echo $DEBIAN_FRONTEND
      # - run:
      #     name: Install the required packages
      #     command: "apt-get install -y g++ gcc python python3"
      # - run:
      #     name: checks integrity of the packages
      #     command: "g++ -v && which g++ && python --version && which python && python3 --version && which python3"

# CENTOS
  job-2-centos:
    docker:
      - image: "centos:latest"
    steps:
      - checkout
      - run:
          name: Check platform
          command: "uname -a"
      - run:
          name: Check content of the repo
          command: "ls -la"

workflows:
  version: 2.1
  start-containers:
    jobs:
      # - job-0-debian
      - job-1-ubuntu
      # - job-2-centos
