version: 2.1

jobs:
  job-0-debian:
    docker:
      - image: "debian:latest"
    steps:
      - checkout
      - run:
          name: Check platform
          command: " uname -a"
      - run:
          name: Check content of the repo
          command: "ls -la"
  job-1-ubuntu:
    docker:
      - image: "ubuntu:latest"
    steps:
      - checkout
      - run:
          name: Update and install sudo
          command: "apt-get update && apt-get install -y sudo &&  rm -rf /var/lib/apt/lists/* "
      - run:
          name: Install the required packages
          command: "sudo apt-get install -y g++ && sudo apt-get install -y python && sudo apt-get install -y python3"
      - run:
          name: checks integrity of the packages
          command: "g++ -v && which g++ && python -v && which python && python3 -v && which python3"
  job-2-centos:
    docker:
      - image: "centos:latest"
    steps:
      - checkout
      - run:
          name: Check platform
          command: "uname -a"
      - run:
          name: Check content of the repo
          command: "ls -la"

workflows:
  version: 2.1
  start-containers:
    jobs:
      # - job-0-debian
      - job-1-ubuntu
      # - job-2-centos
